/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dapur.ui;

import dapur.helper.ConnectionHelper;
import dapur.helper.MenuManager;
import dapur.helper.pemesanan_manajer;
import dapur.model.AkunStatic;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import dapur.model.menu;
import dapur.model.paketStatic;
import dapur.model.pemesanan;
import dapur.model.pemesananStatic;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Farhansw
 */
public class mainwindow extends javax.swing.JFrame {
pemesanan_manajer pemesananGlobal; 
menu menuGlobal;
    int id_akun = AkunStatic.getId_akun();
    String namaUser = AkunStatic.getNama_customer();
    String namaPaket = paketStatic.getNama_paket();
    String hargaPaket = paketStatic.getHarga_paket();
    
    /**
     * Creates new form NewJFrame
     */
    public mainwindow() {
        initComponents();
        setLocationRelativeTo(null);
        lbNama.setText(namaUser);
    }

    public void showMessage(String message, int type){
        if (type == 1){
            JOptionPane.showMessageDialog(this, message, "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    public void clear(){
        tfNamaPaket.setText("");
        tfHarga.setText("");
        tfJumlah.setText("");
        tfTotalharga.setText("");
    }
    public void loadDataPaket(){
        tfNamaPaket.setText(namaPaket);
        tfHarga.setText(hargaPaket);
        tfTotalharga.setText(hargaPaket);
    }
    
    private void getTotal() {
        try {
            int harga = Integer.parseInt(tfHarga.getText());
            int jumlah = Integer.parseInt(tfJumlah.getText());
            int total = (harga * jumlah);
            tfTotalharga.setText(String.valueOf(total));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfTotalharga = new javax.swing.JTextField();
        tfHarga = new javax.swing.JTextField();
        btPaket = new javax.swing.JButton();
        btBayar = new javax.swing.JButton();
        tfJumlah = new javax.swing.JTextField();
        tfNamaPaket = new javax.swing.JTextField();
        btKeluar = new javax.swing.JButton();
        btPesan = new javax.swing.JButton();
        lbNama = new javax.swing.JLabel();
        btRefresh = new javax.swing.JButton();
        btHitung = new javax.swing.JButton();

        jTextField4.setText("jTextField4");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dapur Bu Yoyok");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Welcome ");

        jLabel2.setText("Nama Paket   :");

        jLabel3.setText("Harga   :");

        jLabel4.setText("Jumlah Pesanan   :");

        jLabel5.setText("Total Harga   :");

        tfTotalharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalhargaActionPerformed(evt);
            }
        });

        btPaket.setText("Pilih Paket Lainya");
        btPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPaketActionPerformed(evt);
            }
        });

        btBayar.setText("Bayar");
        btBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBayarActionPerformed(evt);
            }
        });

        btKeluar.setText("Keluar");
        btKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKeluarActionPerformed(evt);
            }
        });

        btPesan.setText("Pesan");
        btPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesanActionPerformed(evt);
            }
        });

        lbNama.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbNama.setText("Nama");

        btRefresh.setText("Refresh");
        btRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefreshActionPerformed(evt);
            }
        });

        btHitung.setText("Hitung");
        btHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(tfTotalharga))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btRefresh)
                                .addGap(18, 18, 18)
                                .addComponent(btPesan)
                                .addGap(18, 18, 18)
                                .addComponent(btBayar)
                                .addGap(18, 18, 18)
                                .addComponent(btKeluar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(35, 35, 35)
                                .addComponent(tfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btHitung))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfHarga)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tfNamaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btPaket))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbNama)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNama, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNamaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPaket))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btHitung))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfTotalharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBayar)
                    .addComponent(btPesan)
                    .addComponent(btKeluar)
                    .addComponent(btRefresh))
                .addGap(30, 30, 30))
        );

        jLabel1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTotalhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalhargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalhargaActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBayarActionPerformed
        // TODO add your handling code here:
       try{
            Connection conn = ConnectionHelper.getConnection();
            Statement st = conn.createStatement();
            String sql = "SELECT * FROM pemesanan WHERE id_akun = '"+id_akun+"'";
            ResultSet rs = st.executeQuery(sql);

            if(rs.next()){        
                pemesananStatic.setId_pemesanan(rs.getInt("id_pemesanan"));
                pemesananStatic.setTotal_harga(rs.getInt("total_harga"));
                new windows_pembayaran().setVisible(true);
                dispose();
            }
        }catch(SQLException e){
            Logger.getLogger(mainwindow.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btBayarActionPerformed

    private void btPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPaketActionPerformed
        // TODO add your handling code here:
        new window_pilih_paket().setVisible(true);
        dispose();
    }//GEN-LAST:event_btPaketActionPerformed

    private void btKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKeluarActionPerformed
        // TODO add your handling code here:
        clear();
        showMessage("Anda berhasil logout!", 1);
        dispose();
        new LoginWindow().setVisible(true);
    }//GEN-LAST:event_btKeluarActionPerformed

    private void btPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesanActionPerformed
        // TODO add your handling code here:
        pemesanan pt = new pemesanan();
        pt.setTotal_harga(Integer.parseInt(tfTotalharga.getText()));
        pt.setJumlah(Integer.parseInt(tfJumlah.getText()));
        try{
            Connection conn = ConnectionHelper.getConnection();
            PreparedStatement pstmn = conn.prepareStatement("insert into pemesanan (id_pemesanan, "
                + "id_paket, id_akun, nama_paket, harga_paket, jumlah, total_harga) values (?, ?, ?, ?, ?, ?, ?)");
            pstmn.setInt(1, pt.getId_pemesanan());
            pstmn.setInt(2, paketStatic.getId_paket());
            pstmn.setInt(3, AkunStatic.getId_akun());
            pstmn.setString(4, paketStatic.getNama_paket());
            pstmn.setString(5, paketStatic.getHarga_paket());
            pstmn.setInt(6, pt.getJumlah());
            pstmn.setInt(7, pt.getTotal_harga());
            pstmn.execute();
            showMessage("Pesanan telah ditambahkan, Silahkan lanjut ke pembayaran", 1);
            //new PembayaranWindow().setVisible(true);
        }catch(SQLException e){
            Logger.getLogger(mainwindow.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btPesanActionPerformed

    private void btRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefreshActionPerformed
        // TODO add your handling code here:
        loadDataPaket();
        try{
            Connection conn = ConnectionHelper.getConnection();
            Statement st = conn.createStatement();
            String sql = "SELECT * FROM pemesanan WHERE id_akun = '"+id_akun+"'";
            ResultSet rs = st.executeQuery(sql);

            if(rs.next()){        
                tfNamaPaket.setText(rs.getString("nama_paket"));
                tfHarga.setText(rs.getString("harga_paket"));
                tfJumlah.setText(String.valueOf(rs.getInt("jumlah")));
                tfTotalharga.setText(String.valueOf(rs.getInt("total_harga")));
                showMessage("Data telah di refresh", 1);
            }
        }catch(SQLException e){
            Logger.getLogger(mainwindow.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btRefreshActionPerformed

    private void btHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHitungActionPerformed
        // TODO add your handling code here:
        getTotal();
    }//GEN-LAST:event_btHitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainwindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBayar;
    private javax.swing.JButton btHitung;
    private javax.swing.JButton btKeluar;
    private javax.swing.JButton btPaket;
    private javax.swing.JButton btPesan;
    private javax.swing.JButton btRefresh;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lbNama;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfJumlah;
    private javax.swing.JTextField tfNamaPaket;
    private javax.swing.JTextField tfTotalharga;
    // End of variables declaration//GEN-END:variables
}
